configure[.in]: add support for -Wdate-time 	lib/ipv6calchelp.c: remove displaying compile time (https://github.com/pbiering/ipv6calc/issues/41)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4612,6 +4612,39 @@ fi
 rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
 		CFLAGS="$CFLAGS_SAVE"
 
+		{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: *** check for CFLAGS: -Wdate-time" >&5
+printf "%s\n" "*** check for CFLAGS: -Wdate-time" >&6; }
+		CFLAGS_SAVE="$CFLAGS"
+		CFLAGS="$CFLAGS -Werror -Wdate-time"
+		cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+int a=1;
+int
+main (void)
+{
+
+  ;
+  return 0;
+}
+
+_ACEOF
+if ac_fn_c_try_compile "$LINENO"
+then :
+
+				{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: *** CFLAGS supported: -Wdate-time" >&5
+printf "%s\n" "*** CFLAGS supported: -Wdate-time" >&6; }
+				# disable errors related to deprecated-declarations
+				CFLAGS_EXTRA="${CFLAGS_EXTRA:+$CFLAGS_EXTRA }-Wdate-time"
+
+else $as_nop
+
+				{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: *** missing CFLAGS support: -Wdate-time" >&5
+printf "%s\n" "$as_me: WARNING: *** missing CFLAGS support: -Wdate-time" >&2;}
+
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
+		CFLAGS="$CFLAGS_SAVE"
+
 fi
 
 
