bugfix

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4759,6 +4759,56 @@ $as_echo "$as_me: WARNING: GeoIP library header files were found but not support
 
 fi
 
+
+			{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for GeoIP_cleanup in -lGeoIP" >&5
+$as_echo_n "checking for GeoIP_cleanup in -lGeoIP... " >&6; }
+if ${ac_cv_lib_GeoIP_GeoIP_cleanup+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lGeoIP  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char GeoIP_cleanup ();
+int
+main ()
+{
+return GeoIP_cleanup ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_GeoIP_GeoIP_cleanup=yes
+else
+  ac_cv_lib_GeoIP_GeoIP_cleanup=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_GeoIP_GeoIP_cleanup" >&5
+$as_echo "$ac_cv_lib_GeoIP_GeoIP_cleanup" >&6; }
+if test "x$ac_cv_lib_GeoIP_GeoIP_cleanup" = xyes; then :
+
+
+$as_echo "#define SUPPORT_GEOIP_CLEANUP 1" >>confdefs.h
+
+
+else
+
+				{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: GeoIP library header files were found but not supporting GeoIP_cleanup (will use workaround)." >&5
+$as_echo "$as_me: WARNING: GeoIP library header files were found but not supporting GeoIP_cleanup (will use workaround)." >&2;}
+
+fi
+
 		else
 			{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: GeoIP IPv6 support compatibility mode enabled (supporting 1.4.5)." >&5
 $as_echo "$as_me: WARNING: GeoIP IPv6 support compatibility mode enabled (supporting 1.4.5)." >&2;}
