tools/DBIP-update.sh[.in]: add option for URL to download "full" database

diff --git a/tools/DBIP-update.sh.in b/tools/DBIP-update.sh.in
--- a/tools/DBIP-update.sh.in
+++ b/tools/DBIP-update.sh.in
@@ -5,7 +5,7 @@
 # Project    : ipv6calc/DBIP
 # File       : DBIP-update.sh
 # Version    : $Id$
-# Copyright  : 2014-2015 by Peter Bieringer <pb (at) bieringer.de>
+# Copyright  : 2014-2017 by Peter Bieringer <pb (at) bieringer.de>
 # License    : GNU GPL version 2
 
 DBIP_DAT_DIR_DEFAULT="@DBIP_DB@"
@@ -18,30 +18,41 @@ DBIP_GENERATOR_LIST="./DBIP-generate-db.pl /usr/share/ipv6calc/tools/DBIP-genera
 
 help() {
 	cat <<END
-Usage: $(basename "$0") [-s] [-D <dir>]
+Usage: $(basename "$0") [-s] [-D <dir>] [-U <url>]
 	-s		skip download
+	-g		skip generation of database file
 	-D <dir>	database directory (optional)
+	-U <url>	use URL to download full database
 
 	database directory: $DBIP_DAT_DIR (default: $DBIP_DAT_DIR_DEFAULT)
 
  it honors externally defined environment value: DBIP_DAT_DIR
 
  this script (and its helper scripts) will download data from
- DB-IP.com (free versions) and generate Berkeley DB files for ipv6calc
+ DB-IP.com (default: free versions) and generate Berkeley DB files for ipv6calc
  "DBIP" database support
 
  DBIP_DAT_URL_BASE=$DBIP_DAT_URL_BASE
  DBIP_DAT_FILES=$DBIP_DAT_FILES
+
+ in case -U <url> (take URL from subscription e-mail) is provided, it downloads the full database
 END
 }
 
-while getopts "D:sh\?" opt; do
+while getopts "D:U:gsh\?" opt; do
 	case $opt in
 	    s)
 		skip_download=1
 		;;
+	    g)
+		skip_generation=1
+		;;
 	    D)
-		DBIP_DAT_DIR=$OPTARG
+		DBIP_DAT_DIR="$OPTARG"
+		;;
+	    U)
+		DBIP_URL="$OPTARG"
+		DBIP_DAT_FILES="dbip-full-%Y-%m.csv.gz"
 		;;
 	    *)
 		help
@@ -92,19 +103,29 @@ if [ "$skip_download" != "1" ]; then
 
 		file_dest="$DBIP_DAT_DIR/`basename "$file"`"
 
-		echo "INFO  : try to download file: $file ($file_dest)"
-		wget -q -O "$file_dest" "$DBIP_DAT_URL_BASE$file"
-		if [ $? -ne 0 ]; then
-			echo "ERROR : download of file not successful: $file ($file_dest)"
-			continue
-			download_result=0
+		if [ -z "$DBIP_URL" ]; then
+			echo "INFO  : try to download file: $file ($file_dest)"
+			wget -q -O "$file_dest" "$DBIP_DAT_URL_BASE$file"
+			if [ $? -ne 0 ]; then
+				echo "ERROR : download of file not successful: $file ($file_dest)"
+				continue
+				download_result=0
+			fi
+		else
+			echo "INFO  : try to download file: $DBIP_URL ($file_dest)"
+			wget -q -O "$file_dest" "$DBIP_URL"
+			if [ $? -ne 0 ]; then
+				echo "ERROR : download of file not successful: $DBIP_URL ($file_dest)"
+				continue
+				download_result=0
+			fi
 		fi
-		echo "INFO  : download of file successful: $file ($file_dest)"
+		echo "INFO  : download of file successful: $DBIP_URL ($file_dest)"
 	done
 fi
 
 # create db files from downloaded files
-if [ "$download_result" = "1" ]; then
+if [ "$download_result" = "1" -a "$skip_generation" != "1" ]; then
 	for file in $DBIP_DAT_FILES; do
 		time_begin=$(date '+%s')
 		echo "INFO  : begin $(date '+%Y%m%d-%H%M%S')"
