spec: add requirement "unzip" (for IP2Location-update.sh)        tools/IP2Location-update.sh: check for existing "unzip"

diff --git a/tools/IP2Location-update.sh.in b/tools/IP2Location-update.sh.in
--- a/tools/IP2Location-update.sh.in
+++ b/tools/IP2Location-update.sh.in
@@ -131,6 +131,12 @@ if [ ! -w "$IP2LOCATION_DAT_DIR" ]; then
 	exit 1
 fi
 
+# required binary check
+if ! which unzip >/dev/null 2>&1; then
+	echo "ERROR : missing binary: unzip"
+	exit 1
+fi
+
 
 # Download and unpack non-sample files
 for list in IP2LOCATION_DAT_FILES_LITE IP2LOCATION_DAT_FILES IP2LOCATION_DAT_FILES_LITE_FREE IP2LOCATION_DAT_FILES_SAMPLE; do
